# -*- coding: utf-8 -*-
"""Softmax Activation Function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B8W6uGkegNXzqrD1lIZHLI-PHVewtEfK

>$\sigma(x_j) = \frac{e^{x_j}}{\sum_i e^{x_j}}$
"""

import numpy as np
L = [5,6,7]

def softmax(L):
  exp_L = np.exp(L)
  sum_exp_L = sum(exp_L)
  result = []
  for i in exp_L:
    result.append(i*1.0/sum_exp_L)
  return result

print(softmax(L))

